/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Georgi
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class Addcv_frame extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public Addcv_frame() {
        
        initComponents();
        conn = javaconnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalInfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        input_surname = new javax.swing.JTextField();
        input_nationality = new javax.swing.JTextField();
        input_living = new javax.swing.JTextField();
        birthPanel = new javax.swing.JPanel();
        input_birthday = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        input_phone = new javax.swing.JTextField();
        input_mail = new javax.swing.JTextField();
        action_clear1 = new javax.swing.JButton();
        input_gender = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        educationPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        input_additional = new javax.swing.JTextArea();
        action_clear2 = new javax.swing.JButton();
        input_language = new javax.swing.JTextField();
        highest_degree = new javax.swing.JTextField();
        lang_pts = new javax.swing.JComboBox();
        highest_degree_pts = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        prev_degree1_pts = new javax.swing.JComboBox();
        prev_degree1 = new javax.swing.JTextField();
        prev_degree2 = new javax.swing.JTextField();
        prev_degree2_pts = new javax.swing.JComboBox();
        prev_degree3 = new javax.swing.JTextField();
        prev_degree3_pts = new javax.swing.JComboBox();
        prev_degree4_pts = new javax.swing.JComboBox();
        prev_degree4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        profExpPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_job3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        input_job1 = new javax.swing.JTextArea();
        jLabel48 = new javax.swing.JLabel();
        input_years1 = new javax.swing.JComboBox();
        input_years2 = new javax.swing.JComboBox();
        jLabel49 = new javax.swing.JLabel();
        input_years3 = new javax.swing.JComboBox();
        input_years4 = new javax.swing.JComboBox();
        action_clear3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        input_job2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        input_job4 = new javax.swing.JTextArea();
        footerPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        action_home = new javax.swing.JButton();
        action_clearall = new javax.swing.JButton();
        action_save = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        input_type = new javax.swing.JComboBox();
        sliderPanel = new javax.swing.JPanel();
        slider_points = new javax.swing.JSlider();
        jLabel20 = new javax.swing.JLabel();
        action_calculate = new javax.swing.JButton();
        overall_pts = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, null, new java.awt.Color(255, 255, 255)));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        personalInfoPanel.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nationality:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Living in:");

        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });

        input_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_birthdayActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("dd/mm/yyyy");

        javax.swing.GroupLayout birthPanelLayout = new javax.swing.GroupLayout(birthPanel);
        birthPanel.setLayout(birthPanelLayout);
        birthPanelLayout.setHorizontalGroup(
            birthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthPanelLayout.createSequentialGroup()
                .addComponent(input_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        birthPanelLayout.setVerticalGroup(
            birthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, birthPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(birthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
        );

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phone:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("E-mail:");

        action_clear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/edit-clear.png"))); // NOI18N
        action_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_clear1ActionPerformed(evt);
            }
        });

        input_gender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        input_gender.setForeground(new java.awt.Color(255, 255, 255));
        input_gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "M", "F" }));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender:");

        javax.swing.GroupLayout personalInfoPanelLayout = new javax.swing.GroupLayout(personalInfoPanel);
        personalInfoPanel.setLayout(personalInfoPanelLayout);
        personalInfoPanelLayout.setHorizontalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(input_surname)
                        .addComponent(input_living)
                        .addComponent(input_nationality)
                        .addComponent(birthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(input_name)
                        .addComponent(input_phone)
                        .addComponent(input_mail)))
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(action_clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        personalInfoPanelLayout.setVerticalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(input_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(input_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(birthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(input_living, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(input_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(input_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(action_clear1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personal Information", personalInfoPanel);

        educationPanel.setOpaque(false);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        input_additional.setColumns(20);
        input_additional.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        input_additional.setLineWrap(true);
        input_additional.setRows(5);
        input_additional.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(input_additional);

        action_clear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/edit-clear.png"))); // NOI18N
        action_clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_clear2ActionPerformed(evt);
            }
        });

        highest_degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highest_degreeActionPerformed(evt);
            }
        });

        lang_pts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lang_pts.setForeground(new java.awt.Color(255, 255, 255));
        lang_pts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5" }));
        lang_pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lang_ptsActionPerformed(evt);
            }
        });

        highest_degree_pts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        highest_degree_pts.setForeground(new java.awt.Color(255, 255, 255));
        highest_degree_pts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "High School", "Diploma", "Bachelor", "Master", "Ph.D" }));
        highest_degree_pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highest_degree_ptsActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Languages");

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Highest degree:");

        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("№");

        jLabel47.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Additional:");

        prev_degree1_pts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prev_degree1_pts.setForeground(new java.awt.Color(255, 255, 255));
        prev_degree1_pts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "High School", "Diploma", "Bachelor", "Master", "Ph.D" }));
        prev_degree1_pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_degree1_ptsActionPerformed(evt);
            }
        });

        prev_degree2_pts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prev_degree2_pts.setForeground(new java.awt.Color(255, 255, 255));
        prev_degree2_pts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "High School", "Diploma", "Bachelor", "Master", "Ph.D" }));
        prev_degree2_pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_degree2_ptsActionPerformed(evt);
            }
        });

        prev_degree3_pts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prev_degree3_pts.setForeground(new java.awt.Color(255, 255, 255));
        prev_degree3_pts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "High School", "Diploma", "Bachelor", "Master", "Ph.D" }));
        prev_degree3_pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_degree3_ptsActionPerformed(evt);
            }
        });

        prev_degree4_pts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prev_degree4_pts.setForeground(new java.awt.Color(255, 255, 255));
        prev_degree4_pts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "High School", "Diploma", "Bachelor", "Master", "Ph.D" }));
        prev_degree4_pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_degree4_ptsActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Previous degree:");

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(action_clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(educationPanelLayout.createSequentialGroup()
                                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prev_degree2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prev_degree3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prev_degree2_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prev_degree3_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(educationPanelLayout.createSequentialGroup()
                                .addComponent(highest_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(highest_degree_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(educationPanelLayout.createSequentialGroup()
                                .addComponent(input_language, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lang_pts, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel39)
                            .addGroup(educationPanelLayout.createSequentialGroup()
                                .addComponent(prev_degree1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prev_degree1_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(educationPanelLayout.createSequentialGroup()
                                .addComponent(prev_degree4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prev_degree4_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel47))
                        .addGap(0, 189, Short.MAX_VALUE))))
        );

        educationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {highest_degree, input_language});

        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educationPanelLayout.createSequentialGroup()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(action_clear2))
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46)
                            .addComponent(lang_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(highest_degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(highest_degree_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prev_degree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prev_degree1_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prev_degree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prev_degree2_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prev_degree3_pts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prev_degree3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prev_degree4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prev_degree4_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Education", educationPanel);

        profExpPanel.setOpaque(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        input_job3.setColumns(20);
        input_job3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        input_job3.setLineWrap(true);
        input_job3.setRows(5);
        input_job3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(input_job3);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        input_job1.setColumns(20);
        input_job1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        input_job1.setLineWrap(true);
        input_job1.setRows(5);
        input_job1.setWrapStyleWord(true);
        input_job1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(input_job1);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Years:");

        input_years1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        input_years1.setForeground(new java.awt.Color(255, 255, 255));
        input_years1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        input_years1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_years1ActionPerformed(evt);
            }
        });

        input_years2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        input_years2.setForeground(new java.awt.Color(255, 255, 255));
        input_years2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        input_years2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_years2ActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Previous Jobs:");

        input_years3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        input_years3.setForeground(new java.awt.Color(255, 255, 255));
        input_years3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        input_years3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_years3ActionPerformed(evt);
            }
        });

        input_years4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        input_years4.setForeground(new java.awt.Color(255, 255, 255));
        input_years4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        input_years4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_years4ActionPerformed(evt);
            }
        });

        action_clear3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/edit-clear.png"))); // NOI18N
        action_clear3.setOpaque(false);
        action_clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_clear3ActionPerformed(evt);
            }
        });

        jScrollPane4.setBorder(null);

        input_job2.setColumns(20);
        input_job2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        input_job2.setLineWrap(true);
        input_job2.setRows(5);
        input_job2.setWrapStyleWord(true);
        input_job2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setViewportView(input_job2);

        jScrollPane5.setBorder(null);

        input_job4.setColumns(20);
        input_job4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        input_job4.setLineWrap(true);
        input_job4.setRows(5);
        input_job4.setWrapStyleWord(true);
        input_job4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane5.setViewportView(input_job4);

        javax.swing.GroupLayout profExpPanelLayout = new javax.swing.GroupLayout(profExpPanel);
        profExpPanel.setLayout(profExpPanelLayout);
        profExpPanelLayout.setHorizontalGroup(
            profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profExpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profExpPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profExpPanelLayout.createSequentialGroup()
                                .addGap(0, 220, Short.MAX_VALUE)
                                .addComponent(action_clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profExpPanelLayout.createSequentialGroup()
                                .addComponent(input_years4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(profExpPanelLayout.createSequentialGroup()
                        .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profExpPanelLayout.createSequentialGroup()
                                .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel49))
                                .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(profExpPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(input_years3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(profExpPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(input_years2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(profExpPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel48))))
                            .addGroup(profExpPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(input_years1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        profExpPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane3, jScrollPane4, jScrollPane5});

        profExpPanelLayout.setVerticalGroup(
            profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profExpPanelLayout.createSequentialGroup()
                .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profExpPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(action_clear3))
                    .addGroup(profExpPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_years1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_years2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_years3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_years4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );

        profExpPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane3, jScrollPane4, jScrollPane5});

        jTabbedPane1.addTab("Professional Experience", profExpPanel);

        footerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        footerPanel.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Save");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Clear All");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Home");

        action_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/home_small.png"))); // NOI18N
        action_home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        action_home.setOpaque(false);
        action_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_homeActionPerformed(evt);
            }
        });

        action_clearall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/clear_small.png"))); // NOI18N
        action_clearall.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        action_clearall.setOpaque(false);
        action_clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_clearallActionPerformed(evt);
            }
        });

        action_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/save_small.png"))); // NOI18N
        action_save.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        action_save.setOpaque(false);
        action_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(action_save)
                        .addGap(41, 41, 41)
                        .addComponent(action_clearall, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(footerPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(47, 47, 47)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                        .addComponent(action_home)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(45, 45, 45))))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(action_home, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(action_clearall)
                    .addComponent(action_save, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel18)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        headerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        headerPanel.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create new profile:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type of the profile:");

        input_type.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        input_type.setForeground(new java.awt.Color(255, 255, 255));
        input_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Manager", "Engineer", "Technician", "Administrative" }));
        input_type.setOpaque(false);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_type, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        sliderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Overall", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        sliderPanel.setOpaque(false);

        slider_points.setBackground(new java.awt.Color(255, 255, 255));
        slider_points.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        slider_points.setForeground(new java.awt.Color(255, 255, 255));
        slider_points.setMajorTickSpacing(10);
        slider_points.setMinorTickSpacing(1);
        slider_points.setPaintLabels(true);
        slider_points.setPaintTicks(true);
        slider_points.setSnapToTicks(true);
        slider_points.setValue(0);
        slider_points.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        slider_points.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Calculate applicant's points:");

        action_calculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/go.png"))); // NOI18N
        action_calculate.setOpaque(false);
        action_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_calculateActionPerformed(evt);
            }
        });

        overall_pts.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        overall_pts.setForeground(new java.awt.Color(51, 51, 51));
        overall_pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overall_ptsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sliderPanelLayout = new javax.swing.GroupLayout(sliderPanel);
        sliderPanel.setLayout(sliderPanelLayout);
        sliderPanelLayout.setHorizontalGroup(
            sliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sliderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sliderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(48, 48, 48)
                        .addComponent(action_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(overall_pts, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(slider_points, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        sliderPanelLayout.setVerticalGroup(
            sliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sliderPanelLayout.createSequentialGroup()
                .addGroup(sliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(action_calculate)
                    .addComponent(overall_pts, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sliderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addGap(18, 18, 18)
                .addComponent(slider_points, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/F14-wallpaper-remix-em-rev2-dark-nosupernova.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(611, 611, 611)
                .addComponent(sliderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(611, 611, 611)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(sliderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
   
    private void action_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_homeActionPerformed
        homePage s = new homePage();
        s.setVisible(true);
        close();
    }//GEN-LAST:event_action_homeActionPerformed

    private void action_clearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_clearallActionPerformed
        input_type.setSelectedIndex(0); //upper panel
        input_name.setText("");
        input_surname.setText("");
        input_nationality.setText("");
        input_living.setText("");
        input_phone.setText("");
        input_birthday.setText("");
        input_mail.setText("");
        input_gender.setSelectedIndex(0);
        input_language.setText("");
        highest_degree.setText("");
        prev_degree1.setText("");
        prev_degree2.setText("");
        prev_degree3.setText("");
        prev_degree4.setText("");
        input_additional.setText("");
        lang_pts.setSelectedIndex(0);
        highest_degree_pts.setSelectedIndex(0);
        prev_degree1_pts.setSelectedIndex(0);
        prev_degree2_pts.setSelectedIndex(0);
        prev_degree3_pts.setSelectedIndex(0);
        prev_degree4_pts.setSelectedIndex(0);
        input_job1.setText("");
        input_job2.setText("");
        input_job3.setText("");
        input_job4.setText("");
        input_years1.setSelectedIndex(0);
        input_years2.setSelectedIndex(0);
        input_years3.setSelectedIndex(0);
        input_years4.setSelectedIndex(0);
        //jToggleButton1.setSelected(false); //togglebuttons set to 0
        //jToggleButton2.setSelected(false);
        //jToggleButton3.setSelected(false);
        overall_pts.setText(""); 
        slider_points.setValue(0); //set the sliders to default position
    }//GEN-LAST:event_action_clearallActionPerformed

    private void action_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_saveActionPerformed
              
        try
        {
            String sql = "INSERT INTO applicants (Name, Surname, Type, Gender, Birthday, Nationality, Living, Phone, Mail, Languages, Highest_degree, Highest_degree_type, Prev_degree1, Prev_degree2, Prev_degree3, Prev_degree4, Additional, Job1, Job2, Job3, Job4, Points, ExYears) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);
            //pst.setString(1, txt_employeeid.getText());
            pst.setString(1, input_name.getText()); //panel1
            pst.setString(2, input_surname.getText());
            pst.setString(3, input_type.getSelectedItem().toString());
            pst.setString(4, input_gender.getSelectedItem().toString());
            pst.setString(5, input_birthday.getText());
            pst.setString(6, input_nationality.getText());
            pst.setString(7, input_living.getText());
            pst.setString(8, input_phone.getText());
            pst.setString(9, input_mail.getText());
            
            pst.setString(10, input_language.getText()); //panel2
            pst.setString(11, highest_degree.getText());
            
            //int test = (int)highest_degree_pts.getSelectedIndex();
            
            pst.setInt(12, (int)highest_degree_pts.getSelectedIndex());///////
            
            pst.setString(13, prev_degree1.getText());
            pst.setString(14, prev_degree2.getText());
            pst.setString(15, prev_degree3.getText());
            pst.setString(16, prev_degree4.getText());
            pst.setString(17, input_additional.getText());
            
            
            pst.setString(18, input_job1.getText()); //panel3
            pst.setString(19, input_job2.getText());
            pst.setString(20, input_job3.getText());
            pst.setString(21, input_job4.getText());          
           
            int sl_value = slider_points.getValue(); //getting the value of slider
            String input_slider_pts = Integer.toString(sl_value);
            
            pst.setString(22, input_slider_pts); //sending the value of slider into DB
            
            //summation of experince years
            int sumYears = (int)input_years1.getSelectedIndex()+(int)input_years2.getSelectedIndex()+
            (int)input_years3.getSelectedIndex()+(int)input_years4.getSelectedIndex();
            //*****************************
            pst.setInt(23, sumYears);
            
            pst.execute();

            JOptionPane.showMessageDialog(null, "Data saved");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //        Update_table();
    }//GEN-LAST:event_action_saveActionPerformed

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void input_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_birthdayActionPerformed

    private void action_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_clear1ActionPerformed
        input_name.setText("");
        input_surname.setText("");
        input_nationality.setText("");
        input_living.setText("");
        input_phone.setText("");
        input_birthday.setText("");
        input_mail.setText("");
        input_gender.setSelectedIndex(0);
      //  Browse_frame.txt_name.setText(""); //this is example for accessing object from another frame. This object must be set to static public from the original frame.
    }//GEN-LAST:event_action_clear1ActionPerformed

    private void action_clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_clear2ActionPerformed
        input_language.setText("");
        highest_degree.setText("");
        prev_degree1.setText("");
        prev_degree2.setText("");
        prev_degree3.setText("");
        prev_degree4.setText("");
        input_additional.setText("");
        lang_pts.setSelectedIndex(0);
        highest_degree_pts.setSelectedIndex(0);
        prev_degree1_pts.setSelectedIndex(0);
        prev_degree2_pts.setSelectedIndex(0);
        prev_degree3_pts.setSelectedIndex(0);
        prev_degree4_pts.setSelectedIndex(0);
    }//GEN-LAST:event_action_clear2ActionPerformed

    private void lang_ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lang_ptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lang_ptsActionPerformed

    private void highest_degree_ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highest_degree_ptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highest_degree_ptsActionPerformed

    private void action_clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_clear3ActionPerformed
        input_job1.setText("");
        input_job2.setText("");
        input_job3.setText("");
        input_job4.setText("");
        input_years1.setSelectedIndex(0);
        input_years2.setSelectedIndex(0);
        input_years3.setSelectedIndex(0);
        input_years4.setSelectedIndex(0);
    }//GEN-LAST:event_action_clear3ActionPerformed

    private void input_years1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_years1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_years1ActionPerformed

    private void input_years2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_years2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_years2ActionPerformed

    private void action_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_calculateActionPerformed
        //int sum = Integer.parseInt(points_schoo
        float calc = (float)lang_pts.getSelectedIndex();
        float calc1 = (float)highest_degree_pts.getSelectedIndex();
    //    int calc2 = (int)prev_degree1_pts.getSelectedIndex();
   //     int calc3 = (int)prev_degree2_pts.getSelectedIndex();
  //      int calc4 = (int)prev_degree3_pts.getSelectedIndex();
//        int calc5 = (int)prev_degree4_pts.getSelectedIndex();
        //int educ = calc1 + calc2 + calc3 + calc4 + calc5;
        float calc6 = (float)input_years1.getSelectedIndex();
        float calc7 = (float)input_years2.getSelectedIndex();
        float calc8 = (float)input_years3.getSelectedIndex();
        float calc9 = (float)input_years4.getSelectedIndex();
        //int years = calc6 + calc7 + calc8 + calc9;
        //float const1 = 100;
        //float const2 = 140;
        float points = (float)(((calc*20*0.7)+(calc1*20*1.2)+((calc6+calc7+calc8+calc9)*5*1.1))/3);
        if (points > 100) {
            points = 100;
        }
        
        slider_points.setValue((int)(points));
        //slider_points.setValue(((calc*10)+(calc1*10)+(calc2*10)+(calc3*10)+(calc4*10)+(calc5*10))+((calc6+calc7+calc8+calc9)*(5/2))/3);
        
        int sl_value = slider_points.getValue(); //getting the value of slider
        String input_slider_pts = Integer.toString(sl_value);
        overall_pts.setText(input_slider_pts);
        
    }//GEN-LAST:event_action_calculateActionPerformed

    private void prev_degree2_ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_degree2_ptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_degree2_ptsActionPerformed

    private void prev_degree3_ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_degree3_ptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_degree3_ptsActionPerformed

    private void prev_degree4_ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_degree4_ptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_degree4_ptsActionPerformed

    private void input_years3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_years3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_years3ActionPerformed

    private void input_years4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_years4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_years4ActionPerformed

    private void overall_ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overall_ptsActionPerformed

    }//GEN-LAST:event_overall_ptsActionPerformed

    private void prev_degree1_ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_degree1_ptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_degree1_ptsActionPerformed

    private void highest_degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highest_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highest_degreeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addcv_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addcv_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addcv_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addcv_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addcv_frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton action_calculate;
    private javax.swing.JButton action_clear1;
    private javax.swing.JButton action_clear2;
    private javax.swing.JButton action_clear3;
    private javax.swing.JButton action_clearall;
    private javax.swing.JButton action_home;
    private javax.swing.JButton action_save;
    private javax.swing.JPanel birthPanel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField highest_degree;
    private javax.swing.JComboBox highest_degree_pts;
    private javax.swing.JTextArea input_additional;
    private javax.swing.JTextField input_birthday;
    private javax.swing.JComboBox input_gender;
    private javax.swing.JTextArea input_job1;
    private javax.swing.JTextArea input_job2;
    private javax.swing.JTextArea input_job3;
    private javax.swing.JTextArea input_job4;
    private javax.swing.JTextField input_language;
    private javax.swing.JTextField input_living;
    private javax.swing.JTextField input_mail;
    private javax.swing.JTextField input_name;
    private javax.swing.JTextField input_nationality;
    private javax.swing.JTextField input_phone;
    private javax.swing.JTextField input_surname;
    private javax.swing.JComboBox input_type;
    private javax.swing.JComboBox input_years1;
    private javax.swing.JComboBox input_years2;
    private javax.swing.JComboBox input_years3;
    private javax.swing.JComboBox input_years4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox lang_pts;
    private javax.swing.JTextField overall_pts;
    private javax.swing.JPanel personalInfoPanel;
    private javax.swing.JTextField prev_degree1;
    private javax.swing.JComboBox prev_degree1_pts;
    private javax.swing.JTextField prev_degree2;
    private javax.swing.JComboBox prev_degree2_pts;
    private javax.swing.JTextField prev_degree3;
    private javax.swing.JComboBox prev_degree3_pts;
    private javax.swing.JTextField prev_degree4;
    private javax.swing.JComboBox prev_degree4_pts;
    private javax.swing.JPanel profExpPanel;
    private javax.swing.JPanel sliderPanel;
    private javax.swing.JSlider slider_points;
    // End of variables declaration//GEN-END:variables
}
