
import com.itextpdf.text.BaseColor;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Date;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;


public class Browse_frame extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Employee_info
     */
    public Browse_frame() {
        initComponents();
        conn = javaconnect.ConnecrDb();
        Update_table();
//      Fillcombo();
    }
    private void Update_table()
    {
        try
        {
            String sql = "SELECT * FROM applicants";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table_applicants.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
                {
                  JOptionPane.showMessageDialog(null, e);
                }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
                    {
                        
                    }
        }
    }
   /* 
    private void Fillcombo()
    {
        try
        {
            String sql = "SELECT * FROM applicants";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                String name = rs.getString("name");
                ComboBox_name.addItem(name);
            }
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(Exception e)
                    {
                        
                    }
        }
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_applicants = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        txt_birthdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_points = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_gender = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_nationality = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_type = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_living = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_lang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_additional = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txt_degree = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_job1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_job2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_job3 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txt_job4 = new javax.swing.JTextArea();
        txt_years = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        create_pdf_button = new javax.swing.JButton();
        home_button = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        delete_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table_applicants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_applicants.setOpaque(false);
        table_applicants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_applicantsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_applicants);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.setOpaque(false);

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_name.setEditable(false);
        txt_name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Surname");

        txt_surname.setEditable(false);
        txt_surname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_birthdate.setEditable(false);
        txt_birthdate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of birth");

        txt_points.setEditable(false);
        txt_points.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Points");

        txt_gender.setEditable(false);
        txt_gender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender");

        txt_nationality.setEditable(false);
        txt_nationality.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nationality");

        txt_type.setEditable(false);
        txt_type.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Position");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_birthdate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel17))
                                .addComponent(jLabel7))
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel9))
                            .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(txt_points, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_points, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Basic Info", jPanel1);

        jPanel5.setOpaque(false);

        txt_living.setEditable(false);
        txt_living.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Living in");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Phone");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("E-Mail");

        txt_mail.setEditable(false);
        txt_mail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_phone.setEditable(false);
        txt_phone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txt_living, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txt_phone))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_living, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contact", jPanel5);

        jPanel2.setOpaque(false);

        txt_lang.setEditable(false);
        txt_lang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Languages");

        txt_additional.setEditable(false);
        txt_additional.setColumns(20);
        txt_additional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_additional.setLineWrap(true);
        txt_additional.setRows(5);
        txt_additional.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_additional);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Additional");

        txt_degree.setEditable(false);
        txt_degree.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Hghest degree");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lang, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_lang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("Education", jPanel2);

        jPanel3.setOpaque(false);

        txt_job1.setEditable(false);
        txt_job1.setColumns(20);
        txt_job1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_job1.setLineWrap(true);
        txt_job1.setRows(5);
        txt_job1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txt_job1);

        txt_job2.setEditable(false);
        txt_job2.setColumns(20);
        txt_job2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_job2.setLineWrap(true);
        txt_job2.setRows(5);
        txt_job2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txt_job2);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Job 1");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Job 2");

        txt_job3.setEditable(false);
        txt_job3.setColumns(20);
        txt_job3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_job3.setLineWrap(true);
        txt_job3.setRows(5);
        txt_job3.setWrapStyleWord(true);
        jScrollPane8.setViewportView(txt_job3);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Job 3");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Job 4");

        txt_job4.setEditable(false);
        txt_job4.setColumns(20);
        txt_job4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_job4.setLineWrap(true);
        txt_job4.setRows(5);
        txt_job4.setWrapStyleWord(true);
        jScrollPane9.setViewportView(txt_job4);

        txt_years.setEditable(false);
        txt_years.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Total years");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(txt_years, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane3, jScrollPane4, jScrollPane8, jScrollPane9});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel32)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txt_years))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Work Experience", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Export to PDF");

        create_pdf_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/print_pdf_small.png"))); // NOI18N
        create_pdf_button.setOpaque(false);
        create_pdf_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_pdf_buttonActionPerformed(evt);
            }
        });

        home_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/home_small.png"))); // NOI18N
        home_button.setOpaque(false);
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Home");

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/delete3.png"))); // NOI18N
        delete_button.setOpaque(false);
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete entry");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel16))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(create_pdf_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_pdf_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/homePage/icons/F14-wallpaper-remix-em-rev2-dark-nosupernova.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void table_applicantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_applicantsMouseClicked
        try
        {
            int row = table_applicants.getSelectedRow();
            String Table_click = (table_applicants.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM applicants WHERE id = '"+Table_click+"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next())
            {
                String add1 = rs.getString("id");
                txt_id.setText(add1);
                String add2 = rs.getString("Name");
                txt_name.setText(add2);
                String add3 = rs.getString("Surname");
                txt_surname.setText(add3);
                String add4 = rs.getString("Type");
                txt_type.setText(add4);
                String add5 = rs.getString("Gender");
                txt_gender.setText(add5 );
                String add6 = rs.getString("Nationality");
                txt_nationality.setText(add6);
                String add7 = rs.getString("Birthday");
                txt_birthdate.setText(add7);
                String add8 = rs.getString("Points");
                txt_points.setText(add8);
                String add9 = rs.getString("Living");
                txt_living.setText(add9);
                String add10 = rs.getString("Mail");
                txt_mail.setText(add10);
                String add11 = rs.getString("Phone");
                txt_phone.setText(add11);
                String add12 = rs.getString("Languages");
                txt_lang.setText(add12);
                String add13 = rs.getString("Job1");
                txt_job1.setText(add13);
                String add14 = rs.getString("Job2");
                txt_job2.setText(add14);
                String add15 = rs.getString("Job3");
                txt_job3.setText(add15);
                String add16 = rs.getString("Job4");
                txt_job4.setText(add16);
                String add17 = rs.getString("Highest_degree");
                txt_degree.setText(add17);
                String add18 = rs.getString("Languages");
                txt_lang.setText(add18);
                String add19 = rs.getString("Additional");
                txt_additional.setText(add19);
                String add20 = rs.getString("ExYears");
                txt_years.setText(add20);
                
            }
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
        finally {
                    try{
                        rs.close(); pst.close(); }
                    catch(Exception e) { } }
        
    }//GEN-LAST:event_table_applicantsMouseClicked

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed

        homePage s = new homePage();
        s.setVisible(true);
        close();
    }//GEN-LAST:event_home_buttonActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void create_pdf_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_pdf_buttonActionPerformed
 
                try {
            OutputStream file = new FileOutputStream(new File("D:\\ProMA+MPRT_Employee_info.pdf"));
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, file);
            document.open();
            
            int row = table_applicants.getSelectedRow();
            String Table_click = (table_applicants.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM applicants WHERE id = '"+Table_click+"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            document.add(new Paragraph("ProMA+ MPRT", FontFactory.getFont(FontFactory.TIMES_BOLD, 18)));
            document.add(new Paragraph("Resume", FontFactory.getFont(FontFactory.TIMES_BOLD, 16)));
            document.add(new Paragraph("  ", FontFactory.getFont(FontFactory.TIMES_BOLD)));
            
            document.add(new Paragraph("Personal Information",FontFactory.getFont(FontFactory.TIMES_BOLD)));
            String idString = "ID:" + "     " + rs.getString("id");
            document.add(new Paragraph(idString,FontFactory.getFont(FontFactory.TIMES)));
            String nameString = "Name:" + "     " + rs.getString("Name");
            document.add(new Paragraph(nameString,FontFactory.getFont(FontFactory.TIMES)));
            String surnameString = "Surname:" + "     " + rs.getString("Surname");
            document.add(new Paragraph(surnameString,FontFactory.getFont(FontFactory.TIMES)));
            String positionString = "Position:" + "     " + rs.getString("Type");
            document.add(new Paragraph(positionString,FontFactory.getFont(FontFactory.TIMES)));
            String genderString = "Gender:" + "     " + rs.getString("Gender");
            document.add(new Paragraph(genderString,FontFactory.getFont(FontFactory.TIMES)));
            String natString = "Nationality:" + "     " + rs.getString("Nationality");
            document.add(new Paragraph(natString,FontFactory.getFont(FontFactory.TIMES)));
            String dobString = "Date of Birth:" + "     " + rs.getString("Birthday");
            document.add(new Paragraph(dobString,FontFactory.getFont(FontFactory.TIMES)));
            String scoreString = "Toral Score:" + "     " + rs.getString("Points");
            document.add(new Paragraph(scoreString,FontFactory.getFont(FontFactory.TIMES)));
            document.add(new Paragraph("  ", FontFactory.getFont(FontFactory.TIMES_BOLD)));
            
           
            document.add(new Paragraph("Contact Information", FontFactory.getFont(FontFactory.TIMES_BOLD)));
            String prString = "Current Residence:" + "     " + rs.getString("Living");
            document.add(new Paragraph(prString,FontFactory.getFont(FontFactory.TIMES)));
            String emString = "E-Mail:" + "     " + rs.getString("Mail");
            document.add(new Paragraph(emString,FontFactory.getFont(FontFactory.TIMES)));
            String pnString = "Phone Number:" + "     " + rs.getString("Phone");
            document.add(new Paragraph(pnString,FontFactory.getFont(FontFactory.TIMES)));
            document.add(new Paragraph("  ", FontFactory.getFont(FontFactory.TIMES_BOLD)));
            
            document.add(new Paragraph("Educational Information", FontFactory.getFont(FontFactory.TIMES_BOLD)));
            String hdString = "Highest Degree:" + "     " + rs.getString("Highest_degree");
            document.add(new Paragraph(hdString,FontFactory.getFont(FontFactory.TIMES)));
            String slString = "Spoken Languages:" + "     " + rs.getString("Languages");
            document.add(new Paragraph(slString,FontFactory.getFont(FontFactory.TIMES)));
            String aiString = "Additional Information:" + "     " + rs.getString("Additional");
            document.add(new Paragraph(aiString,FontFactory.getFont(FontFactory.TIMES)));
            document.add(new Paragraph("  ", FontFactory.getFont(FontFactory.TIMES_BOLD)));
            
            document.add(new Paragraph("Professional Experience", FontFactory.getFont(FontFactory.TIMES_BOLD)));    
            String fjString = "First Job:" + "     " + rs.getString("Job1");
            document.add(new Paragraph(fjString,FontFactory.getFont(FontFactory.TIMES)));
            String sjString = "Second Job:" + "     " + rs.getString("Job2");
            document.add(new Paragraph(sjString,FontFactory.getFont(FontFactory.TIMES)));
            String tjString = "Third Job:" + "     " + rs.getString("Job3");
            document.add(new Paragraph(tjString,FontFactory.getFont(FontFactory.TIMES)));
            String frjString = "Fourth Job:" + "    " + rs.getString("Job4");
            document.add(new Paragraph(frjString,FontFactory.getFont(FontFactory.TIMES)));
            String exString = "Total Years of Experience:" + "     " + rs.getString("ExYears");
            document.add(new Paragraph(exString,FontFactory.getFont(FontFactory.TIMES)));           
            document.add(new Paragraph("  ", FontFactory.getFont(FontFactory.TIMES_BOLD)));

            document.add(new Paragraph(new Date().toString(), FontFactory.getFont(FontFactory.defaultEncoding, 8)));
            document.add(new Paragraph("© 2012-2013 | All rights reserved for University of Siegen", FontFactory.getFont(FontFactory.defaultEncoding, 8)));
            document.close();
            file.close();
 
        } catch (Exception e) {
 
            e.printStackTrace();
        }
              finally {
                    try{
                        rs.close(); pst.close(); }
                    catch(Exception e) { } }

                
         JOptionPane.showMessageDialog(null, "A PDF file of the selected applicant was generated and saved in D:\\ProMA+MPRT_Employee_info.pdf ");

        
    }//GEN-LAST:event_create_pdf_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed

        String sql = "delete from applicants where ID =?";
                try
        {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Entry deleted");

        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
        finally {
                    try{
                        rs.close(); pst.close(); }
                    catch(Exception e) { } }
                
                refresh_table ();
        
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void refresh_table (){
        
        try {
        String sql = "select * from applicants";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        table_applicants.setModel(DbUtils.resultSetToTableModel(rs));
        
    }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
                finally {
                    try{
                        rs.close(); pst.close(); }
                    catch(Exception e) { } }
    }
        
   // public static void create_pdf(String[] args) {
       // try {
            //OutputStream file = new FileOutputStream(new File("D:\\Test.pdf"));
 
           // Document document = new Document();
           // PdfWriter.getInstance(document, file);
 
            //document.open();
           // document.add(new Paragraph("Hello World, iText"));
           // document.add(new Paragraph(new Date().toString()));
 
           // document.close();
           // file.close();
 
      //  } catch (Exception e) {
 
      //      e.printStackTrace();
     //   }
 //   }
    
    //public static void create_pdf(String arg[])throws 
       // Exception { Document document=new Document();
        //PdfWriter.getInstance(document,new FileOutputStream("hello.pdf"));
        //document.open(); document.add(new Paragraph("Hello world this is my first PDF"));
        //document.close(); }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Browse_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Browse_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Browse_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Browse_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Browse_frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_pdf_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton home_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table_applicants;
    private javax.swing.JTextArea txt_additional;
    private javax.swing.JTextField txt_birthdate;
    private javax.swing.JTextField txt_degree;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextArea txt_job1;
    private javax.swing.JTextArea txt_job2;
    private javax.swing.JTextArea txt_job3;
    private javax.swing.JTextArea txt_job4;
    private javax.swing.JTextField txt_lang;
    private javax.swing.JTextField txt_living;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nationality;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_points;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_type;
    private javax.swing.JTextField txt_years;
    // End of variables declaration//GEN-END:variables
}
